### ISSUE TITLE
Lazyness behaviour on vertical vs horizontal mode

### ISSUE THREAD

**Issue by davidcedresx** [jeanverster/chakra-ui-steps#10]
Hi, thank you for such a great component I truly love it.

I have been using it on my desktop just fine, right now I am putting some focus on responsiveness and I found that the stepper will become vertical by default which is great, the issue is that every render function for every step triggers immediately, on the horizontal mode they just trigger when you reach that step.

Sandbox which replicates the issue:
https://codesandbox.io/s/sharp-johnson-l4qyk?file=/src/Test.js

**Comment by jeanverster** [comment]
Hi @davidcedresx - thanks for pointing this out, will try have a look asap 👌🏼

**Comment by jeanverster** [comment]
hey @davidcedresx I've updated the behaviour to only mount the content component when the step is active, I believe this this is the desired behaviour. Will create a release with this update soon. It just occurred to me that it could be nice to have this `lazy` behaviour controlled by a prop 😅  Think I will add this in too at some stage

**Comment by jeanverster** [comment]
Available in 1.1.2
