### ISSUE TITLE
How Can I change the background color of the active steps?

### ISSUE THREAD

**Issue by oguzkaganeren** [jeanverster/chakra-ui-steps#101]
![image](https://user-images.githubusercontent.com/5963437/207399446-7e1920a1-48b5-447d-9fed-cd204a749f19.png)
I want to change the icon background color. How can I do that? (I guess it broke after chakra update)

**Comment by rafaelcastan** [comment]
Hi, I have found a solution for this, in your theme file create a custom theme for the component this way: 


const Steps = {
  ...StepsStyleConfig,
  baseStyle: (props: any) => {
    return {
      stepIconContainer: {
        ...StepsStyleConfig.baseStyle(props).stepIconContainer,
        _activeStep: {
          bg: "red",
        },
      },
    };
  },
};

**Comment by oguzkaganeren** [comment]
It worked but when apply custom theme, then it turns like this
![image](https://user-images.githubusercontent.com/5963437/207948598-bb5b6401-157b-4d47-8e3c-9b9fca66e6e6.png)

**Comment by rafaelcastan** [comment]
Have you tried to set the  orientation property to horizontal?

**Comment by oguzkaganeren** [comment]
```
const CustomSteps = {
  ...StepsStyleConfig,
  baseStyle: (props:any) => ({
    ...StepsStyleConfig.baseStyle(props),
    stepIconContainer: {
      ...StepsStyleConfig.baseStyle(props).stepIconContainer,
      _activeStep: {
        bg: 'red',
      },
    },
  }),
};
```    Thanks a lot, I fixed.

**Comment by danielbuechele** [comment]
I am experiencing the same issue. While customizing the color of the active step fixes the problem, I think this still is a bug, that incorrectly in light mode, the dark mode background color for the active step is used.

**Comment by Aichnerc** [comment]
+1
