### ISSUE TITLE
Feature Suggestion: Ability to know completed state

### ISSUE THREAD

**Issue by rikusen0335** [jeanverster/chakra-ui-steps#102]
*We* might hope that if this lib would provides a state `completed` which to know the step is completed or not through `useSteps`.

My current workaround is to define like `const LAST_STEP = 3` by seeing how many steps are defined in `Steps`.
But this is kinda bad solution.

So current `useSteps` is not a context, well I'd say maybe we give a prop to `Steps` component which is return a callback to get current step state, like `<Steps state={(currentState) => setStep(currentState)}>`, tho this is also bad solution.

I might think another way and implement and PR them... maybe 🤔

**Comment by jeanverster** [comment]
Hey @rikusen0335 I'm not 100% sure I understand? Could you perhaps provide some code as an example of what you're trying to achieve?

**Comment by rikusen0335** [comment]
Thank you for really.
Well, I'm talking about how to determine if all the steps are completed 🙂

Because I need to make some functionality for this.

**Comment by jeanverster** [comment]
Would something like this not work? 🤔 

```js
const completed = activeStep >= steps.length;
```

**Comment by rikusen0335** [comment]
I was using that workaround, but I had some reason that I need this feature... I forgot, it's been awhile :face_palm:

**Comment by rikusen0335** [comment]
Okay well, I'm gonna close this issue. Thank you for the answer!
