### ISSUE TITLE
SystemStyleFunction Not Beong Imported

### ISSUE THREAD

**Issue by ayodeji1167** [jeanverster/chakra-ui-steps#107]
export 'SystemStyleFunction' (imported as 'SystemStyleFunction') was not found in '@chakra-ui/theme-tools' (possible exports: addPrefix, anatomy, blacken, calc, complementary, contrast, createBreakpoints, cssVar, darken, generateStripe, getColor, isAccessible, isDark, isDecimal, isLight, isReadable, lighten, mode, orient, randomColor, readability, toVar, toVarRef, tone, transparentize, whiten)

This is im unable to import `SystemStyleFunction ` from  `@chakra-ui/theme-tools`

im using chakra  ui 2.4.6 it did'nt work so i switched to 2.4.1 , it still didn't work

**Comment by jeanverster** [comment]
Hi @ayodeji1167 - could you perhaps provide me with a codesandbox / stackblitz repro? I just tried in a fresh vite project and all seems to work as expected:

https://stackblitz.com/edit/vitejs-vite-wjszrb?file=src/App.tsx

**Comment by jeanverster** [comment]
Closing this due to no repro, please re-open if you're still running into this issue.
