### ISSUE TITLE
Make error state icon configurable

### ISSUE THREAD

**Issue by SchneckchenAndy** [jeanverster/chakra-ui-steps#109]
Hi there!

I noticed that the docs seem to be a bit out of date and that the icon for the error state example is completely different than the one in the current build. Could there be an option to change this icon like there is for the checkIcon?

PS: I think that the old icon from the docs looks better.

**Comment by jeanverster** [comment]
Hey @SchneckchenAndy - indeed the docs are a bit out of date.. I'm currently working on a new docs site which has better and more accurate examples.. In the meanwhile, you should be able to customise the error icon using the `errorIcon` prop:

**Comment by SchneckchenAndy** [comment]
I am looking forward to the new docs. Thanks for the help!
