### ISSUE TITLE
Can't resolve '@chakra-ui/react-context'

### ISSUE THREAD

**Issue by A7medSa3ed** [jeanverster/chakra-ui-steps#110]
Module not found: Can't resolve '@chakra-ui/react-context' in 'xx\web-design-system\node_modules\chakra-ui-steps\dist/node_modules/chakra-ui-steps/dist/chakra-ui-steps.es.js

**Comment by A7medSa3ed** [comment]
after add @chakra-ui/react-context
this error generated 
![image](https://user-images.githubusercontent.com/18154181/213440937-980563e6-96b3-4dd8-8b87-69e08d21711f.png)

**Comment by jeanverster** [comment]
Hi @A7medSa3ed - could you please share your package.json so I can have a look at which versions you are on?

**Comment by A7medSa3ed** [comment]
@jeanverster 

"dependencies": {
    "@chakra-ui/icon": "^2.0.5",
    "@chakra-ui/react": "^1.8.8",
    "@chakra-ui/react-use-previous": "^2.0.2",
    "@chakra-ui/react-utils": "^1.2.3",
    "@chakra-ui/shared-utils": "^2.0.2",
    "@chakra-ui/system": "^1.11.2",
    "@chakra-ui/theme-tools": "^1.3.6",
    "@chakra-ui/utils": "^2.0.6",
    "@emotion/react": "^11.10.0",
    "@emotion/styled": "^11.10.0",
    "@fontsource/inter": "^4.5.12",
    "@fontsource/tajawal": "^4.5.9",
    "@theme-ui/custom-properties": "^0.14.7",
    "highcharts": "^10.2.1",
    "highcharts-border-radius": "^0.0.4",
    "highcharts-react-official": "^3.1.0",
    "lodash": "^4.17.21",
    "polished": "^4.2.2",
    "rc-pagination": "^3.1.17",
    "rc-steps": "^6.0.0",
    "react-date-object": "^2.1.5",
    "react-dropzone": "^14.2.3",
    "react-multi-date-picker": "^3.3.3",
    "react-select": "^5.4.0",
    "swiper": "^8.4.3"
  },
  "resolutions": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "framer-motion": "4.1.17",
    "webpack": "^4.46.0",
    "typescript": "~4.7.0"
  },
  "scripts": {
    "dev": " run-p *:dev",
    "build": "yarn clean clean &&  cross-env NODE_ENV=production run-p *:build",
    "clean": "del-cli --force dist",
    "lib:bundle": " webpack",
    "lib:types": "tsc --build tsconfig.types.json && tsc-alias tsconfig.json",
    "lib:build": "run-p lib:bundle lib:types",
    "lint": "eslint --ext .js,.jsx,.ts,.tsx src --color",
    "lint:fix": "npm run lint -- --fix",
    "type-check": "tsc --noEmit",
    "format": "prettier --write \"src/**/*.{ts,tsx,scss,css,json,mdx}\"",
    "storybook:dev": " start-storybook -p 6006",
    "storybook:build": " build-storybook",
    "commit:example": "echo 'yarn run commit -- 'v.1.0.1: Fixes'",
    "commit:patch": "yarn version --pre --patch --no-git-tag-version --force",
    "commit:minor": "yarn version --pre --minor --no-git-tag-version --force",
    "commit:major": "yarn version --pre --major --no-git-tag-version --force",
    "precommit": "yarn run commit:patch && git add --all",
    "publish:loc": " yarn build && yalc publish --no-scripts"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "lint-staged": {
    "src/**/*.{js,jsx,ts,tsx,json}": [
      "eslint --cache --fix --resolve-plugins-relative-to"
    ],
    "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}": [
      "prettier --write"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.18.10",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.18.6",
    "@babel/plugin-proposal-optional-chaining": "^7.18.9",
    "@babel/preset-env": "^7.18.10",
    "@babel/preset-react": "^7.18.6",
    "@babel/preset-typescript": "^7.18.6",
    "@figspec/components": "^1.0.1",
    "@figspec/react": "^1.0.2",
    "@hookform/devtools": "^4.2.3",
    "@jackfranklin/test-data-bot": "^2.0.0",
    "@mdx-js/react": "^1.6.22",
    "@storybook/addon-a11y": "^6.5.14",
    "@storybook/addon-actions": "^6.5.14",
    "@storybook/addon-console": "^1.2.3",
    "@storybook/addon-docs": "^6.5.14",
    "@storybook/addon-essentials": "^6.5.14",
    "@storybook/addon-links": "^6.5.14",
    "@storybook/node-logger": "^6.5.14",
    "@storybook/react": "^6.5.14",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@types/react-select": "^5.0.1",
    "@typescript-eslint/eslint-plugin": "^5.33.0",
    "@typescript-eslint/parser": "^5.33.0",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.5",
    "cross-env": "^7.0.3",
    "css-loader": "^5.0.1",
    "del-cli": "^5.0.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-react-app": "^7.0.1",
    "eslint-import-resolver-typescript": "^3.4.1",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.30.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "faker": "^6.6.6",
    "file-loader": "^6.2.0",
    "husky": "^4.3.8",
    "install-peers-cli": "^2.2.0",
    "lint-staged": "^13.0.3",
    "mini-css-extract-plugin": "^1.3.4",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.7.1",
    "prettier-eslint": "^15.0.1",
    "prettier-eslint-cli": "^6.0.1",
    "react-hook-form": "^7.36.1",
    "storybook-addon-designs": "^6.3.1",
    "storybook-mobile": "^1.0.0",
    "style-loader": "^1.2.1",
    "terser-webpack-plugin": "^4.2.3",
    "ts-dedent": "^2.2.0",
    "tsc-alias": "^1.7.0",
    "typescript": "~4.7.0",
    "webpack-cli": "^4.9.2",
    "yalc": "^1.0.0-pre.53"
  },
  "overrides": {
    "@mdx-js/react": {
      "react": "$react"
    }
  },
  "peerDependencies": {
    "framer-motion": "4.1.17",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn run precommit"
    }
  }

**Comment by A7medSa3ed** [comment]
@jeanverster 
i use 1.4.0 and 2.0.1 and 1.6.1 for chakra-ui-steps all versions give me the same issue

**Comment by jeanverster** [comment]
Is there a specific reason you have separate versions of: 

"@chakra-ui/react-use-previous": "^2.0.2",
"@chakra-ui/react-utils": "^1.2.3",
"@chakra-ui/shared-utils": "^2.0.2",
"@chakra-ui/system": "^1.11.2",
"@chakra-ui/theme-tools": "^1.3.6",
"@chakra-ui/utils": "^2.0.6",

I believe all of these packages should be installed under `@chakra-ui/react`? Which in turn should handle their versions. I also noticed you are using @chakra-ui/react < 2, if you want to use the latest version of this component could you try updating to v2+ and removing all the extra dependencies listed above? 

If it's not possible to update your chakra version could you try installing [1.8.0](https://www.npmjs.com/package/chakra-ui-steps/v/1.8.0) of `chakra-ui-steps` ?

**Comment by A7medSa3ed** [comment]
i will try to use 1.8.0 for chakra-ui-steps and inform u now

**Comment by A7medSa3ed** [comment]
@jeanverster 

thank you for your support 
it's worked for me for 1.8.0 and removing "@chakra-ui/utils" from package json

**Comment by A7medSa3ed** [comment]
![image](https://user-images.githubusercontent.com/18154181/215316303-d3266172-4804-40da-ac5c-d34d59ad47d8.png)

@jeanverster 

i face this issue when build my design system 
it's work fine but it's  only through this error when build it
