### ISSUE TITLE
`labelOrientation` prop no longer exists

### ISSUE THREAD

**Issue by wub** [jeanverster/chakra-ui-steps#116]
Hi there, the documentation says to set `labelOrientation="vertical"` to put the labels below the step circles.

After updating to v2.x, this prop no longer exists. Is this intended? If so, I'll go ahead and reimplement this with custom code.

Thanks!

**Comment by jeanverster** [comment]
Hi @wub - sorry about this, I probably forgot to update the documentation to mention that instead of label orientation you can now use the "circles-alt" variant instead.. That should have the same effect.. Let me know if that works 👍🏼

**Comment by wub** [comment]
Thanks @jeanverster, that's perfect!

**Comment by FreddieFruitSticks** [comment]
Hi. Sorry, total noob here. Where do I set the "circles-alt" variant option? Cant find it :(

**Comment by FreddieFruitSticks** [comment]
Thank you!
