### ISSUE TITLE
Responsive not working

### ISSUE THREAD

**Issue by ridhosatriawan** [jeanverster/chakra-ui-steps#118]
Hello @jeanverster  thanks for creating this package, but i have problem with it. i use this with nextjs and the responsive not working

this my code
theme.tsx 
`import { extendTheme } from "@chakra-ui/react";
import "@fontsource/open-sans/300.css";
import "@fontsource/open-sans/400.css";
import "@fontsource/open-sans/700.css";
import { StepsTheme as Steps } from "chakra-ui-steps";

export const theme = extendTheme({
  components: {
    Steps,
  },
  colors: {
    brand: {
      100: "#d60f16",
    },
  },
  fonts: {
    body: "Open Sans, sans-serif",
  },
});
`

steps.tsx
`import React from "react";
import { Step, Steps, useSteps } from "chakra-ui-steps";
import { Flex, Button } from "@chakra-ui/react";

type stepsProps = {};

const StepsRegister: React.FC<stepsProps> = () => {
  const steps = [
    { label: "Pilih Provinsi / Kota", content: "1" },
    { label: "Pilih Calon", content: "2" },
    { label: "Isi Data Diri", content: "3" },
    { label: "Ajukan Dukungan", content: "4" },
    { label: "Cetak Kartu", content: "5" },
  ];
  const { nextStep, prevStep, reset, activeStep } = useSteps({
    initialStep: 0,
  });

  return (
    <Flex flexDir="column" width="100%">
      <Steps activeStep={activeStep}>
        {steps.map(({ label, content }) => (
          <Step label={label} key={label}>
            {content}
          </Step>
        ))}
      </Steps>
      {activeStep === steps.length ? (
        <Flex p={4}>
          <Button mx="auto" size="sm" onClick={reset}>
            Reset
          </Button>
        </Flex>
      ) : (
        <Flex width="100%" justify="flex-end">
          <Button
            isDisabled={activeStep === 0}
            mr={4}
            onClick={prevStep}
            size="sm"
            variant="ghost"
          >
            Prev
          </Button>
          <Button size="sm" onClick={nextStep}>
            {activeStep === steps.length - 1 ? "Finish" : "Next"}
          </Button>
        </Flex>
      )}
    </Flex>
  );
};
export default StepsRegister;
`

thaks

**Comment by jeanverster** [comment]
Hi @ridhosatriawan, I have pushed a fix for this, please let me know if it's still not working as expected
