### ISSUE TITLE
Label Orientation

### ISSUE THREAD

**Issue by adamu-tako** [jeanverster/chakra-ui-steps#129]
The labelOrientation prop does not work.

**Comment by marcoazumo** [comment]
Hello, I was having this same issue, found my answer here https://github.com/jeanverster/chakra-ui-steps/issues/116#issuecomment-1409798460

**Comment by adamu-tako** [comment]
Thank you!

**Comment by jeanverster** [comment]
Sorry for the confusion here @adamu-tako - I'll be sure to update the docs asap!
