### ISSUE TITLE
Bug in Safari

### ISSUE THREAD

**Issue by kotoyama** [jeanverster/chakra-ui-steps#13]
Hi, thanks for your work!
I found a markup bug in mobile Safari.

![photo_2021-07-23_10-35-42](https://user-images.githubusercontent.com/26006369/126741466-9d75a9f1-cc00-4ac7-96fe-3cd42bfaff92.jpg)
![photo_2021-07-23_10-35-41](https://user-images.githubusercontent.com/26006369/126741473-791775ee-d91c-42ea-ad82-2adf524eca3e.jpg)

**Comment by jeanverster** [comment]
Hi @kotoyama - is there any chance you could be seeing a cached version? I've just had a look on my device and it all seems ok 🤷🏼‍♂️

![image](https://user-images.githubusercontent.com/17738943/126743700-1da721d8-ccd1-427f-8d74-0577f0e6c090.png)

**Comment by jeanverster** [comment]
I remember that was a bug in one of the earlier versions but I think it has since been fixed

**Comment by kotoyama** [comment]
@jeanverster no, this issue is also available in my app build
![photo_2021-07-23_01-20-25](https://user-images.githubusercontent.com/26006369/126744333-f7927f5e-48f2-4e77-9c8a-e31b2f12c855.jpg)

**Comment by kotoyama** [comment]
> I remember that was a bug in one of the earlier versions but I think it has since been fixed

I remember a similar problem and I upgraded. Looks like this bug remains in Safari.

**Comment by jeanverster** [comment]
Hmmm, ok I will have a look. What version of iOS are you currently running?

**Comment by jeanverster** [comment]
And what version of `chakra-ui-steps` are you using in your app?

**Comment by kotoyama** [comment]
iOS: 13.5.1
chakra-ui-steps: ^1.0.3

**Comment by jeanverster** [comment]
Thanks! Will keep you updated

**Comment by jeanverster** [comment]
@kotoyama can you install latest version (1.1.3) and see if the issue has been resolved?

**Comment by kotoyama** [comment]
Yeah it's cool! Thank you :)
