### ISSUE TITLE
Vertical orientation with no Collapse

### ISSUE THREAD

**Issue by moosefaceee** [jeanverster/chakra-ui-steps#130]
Hey @jeanverster - looking to use this stepper, vertical, but without the collapse so that the content is full height all the time. Would you be open to accepting/releasing a PR?

**Comment by jeanverster** [comment]
Hey @moosefaceee - sorry for late reply here, been on vacation. Would be happy to accept a PR for this functionality, I think it had been requested previously as well 👌

**Comment by jeanverster** [comment]
This has been added in the latest release with the `expandVerticalSteps` prop, lemme know if you still run into issues.

**Comment by moosefaceee** [comment]
Champion thanks @jeanverster! Will revert back with how it goes.
