### ISSUE TITLE
In vertical mode it would be nice if the step was full width

### ISSUE THREAD

**Issue by jsbroks** [jeanverster/chakra-ui-steps#18]
![image](https://user-images.githubusercontent.com/24920936/127559058-8f3275c4-03e8-4c4c-a9b7-06ad6b842c4b.png)

**Comment by jeanverster** [comment]
Hey @jsbroks - would passing `width="100%"` to the `Step` component not work in this case? Both the `Step` and `Steps` components should accept all the default chakra styling props

**Comment by jsbroks** [comment]
Swt the width does not fix this issue. It looks like step is wrapped inside another div

**Comment by jeanverster** [comment]
Fixed in v.1.3.0

**Comment by jsbroks** [comment]
Youre amazing! 👏
