### ISSUE TITLE
Gray background color on steps

### ISSUE THREAD

**Issue by TheHoltz** [jeanverster/chakra-ui-steps#2]
Hi! The horizontal steps when resized to mobile has this gray background, I'm not sure if is a feature or a bug, but is there a way to disable it? Thank you!

Horizontal on Mobile | Vertical on Mobile
--- | ---
![image](https://user-images.githubusercontent.com/38303017/121525799-24ef2e00-c9cf-11eb-8d06-8834bbbe6cb8.png) | ![image](https://user-images.githubusercontent.com/38303017/121525832-2d476900-c9cf-11eb-9c46-fa65664bf5de.png)

**Comment by jeanverster** [comment]
Hey @TheHoltz - this is definitely not an intended feature 😅 I will have a look at this soon and release a patch, thanks for pointing it out!

**Comment by jeanverster** [comment]
Fixed by #3

**Comment by jeanverster** [comment]
Hey @TheHoltz this fix is available in version 1.0.3 👍🏼
