### ISSUE TITLE
Need step label on center 

### ISSUE THREAD

**Issue by lihsaa591** [jeanverster/chakra-ui-steps#21]
I need to move the step label on the centre but I don't know how to do that. 
![2021-08-03_16-59](https://user-images.githubusercontent.com/81949431/128006361-a3603e5d-5b78-4368-909c-6fe7c52a9c47.png)

**Comment by jeanverster** [comment]
Hi @lihsaa591 this is currently not supported, but I will be happy to add it when I have a gap 👍🏼

**Comment by devioand** [comment]
@jeanverster  When this feature will be available to center the label

**Comment by jeanverster** [comment]
This functionality has been added in version 1.6.0, you can now use the `labelOrientation` prop to create this effect
