### ISSUE TITLE
Color scheme steps inside a modal

### ISSUE THREAD

**Issue by jsbroks** [jeanverster/chakra-ui-steps#22]
In a modal, the stepper form doesn't work well.

What is the suggested or best option for different color schemes? Or maybe using `blackAlpha`/`whiteAlpha` would be a better option than gray.

![image](https://user-images.githubusercontent.com/24920936/128241941-1436d8f1-3332-4681-be28-202f29b6d738.png)

**Comment by jeanverster** [comment]
Doing some issue cleanup, you should now be able to use the `trackColor` prop to change the color here
