### ISSUE TITLE
Add support for clickable steps

### ISSUE THREAD

**Issue by ken-muturi** [jeanverster/chakra-ui-steps#25]
Add support for clickable steps. ie Click on step number/icon to toggle through the steps as an addition to the prev/next buttons.

**Comment by Temidayomichael** [comment]
You can add a Button Icon as custom icon then do onClick to prev or next step functions provided.

**Comment by jeanverster** [comment]
@ken-muturi have been meaning to implement this, will try get around to it asap..

**Comment by ken-muturi** [comment]
cool, we shall be waiting.

> 
> 
> @ken-muturi have been meaning to implement this, will try get around to it asap..

**Comment by ken-muturi** [comment]
> 
> 
> You can add a Button Icon as custom icon then do onClick to prev or next step functions provided.

mhh interesting; let me try it out.

**Comment by jeanverster** [comment]
@ken-muturi this has been added in v.1.4.0  - please note you will need to update your chakra version to at least 1.6.7 in order for the new version to work, sorry for the inconvenience. See clickable steps example below:

```tsx
const steps = [{ label: "Step 1" }, { label: "Step 2" }, { label: "Step 3" }]

export const ClickableSteps = () => {
  const { nextStep, prevStep, reset, activeStep, setStep } = useSteps({
    initialStep: 0,
  })

  return (
    <Flex flexDir="column" width="100%">
      <Steps onClickStep={(step) => setStep(step)} activeStep={activeStep}>
        {steps.map(({ label }, index) => (
          <Step label={label} key={label}>
            <Contents index={index} />
          </Step>
        ))}
      </Steps>
      {activeStep === 3 ? (
        <ResetPrompt onReset={reset} />
      ) : (
        <StepButtons
          nextStep={nextStep}
          prevStep={prevStep}
          prevDisabled={activeStep === 0}
        />
      )}
    </Flex>
  )
}

export default ClickableSteps
```
