### ISSUE TITLE
Steps container

### ISSUE THREAD

**Issue by Temidayomichael** [jeanverster/chakra-ui-steps#26]
Hi thanks for the very useful tool, how can I hide the "1,2,3" strap header please ![image](https://user-images.githubusercontent.com/51400490/134497569-525a88de-185b-4ac2-89d6-5cff52113b02.jpeg)

**Comment by jeanverster** [comment]
Hi @Temidayomichael i'm not sure I understand, do you want to hide the entire steps header? Or change the numbers?

**Comment by Temidayomichael** [comment]
> Hi @Temidayomichael i'm not sure I understand, do you want to hide the entire steps header? Or change the numbers?

I want to hide the entire header

**Comment by jeanverster** [comment]
If you want to hide the header you will only be able to do so with the stepper in `horizontal` orientation, and you can do so by overriding the default `steps` styles like this:
```js
const Steps = {
  ...StepsStyleConfig,
  baseStyle: {
    steps: {
      display: "none",
    },
  },
}

const theme = extendTheme({
  components: {
    Steps,
  },
})
```
