### ISSUE TITLE
Stepper always horizontal on initial load

### ISSUE THREAD

**Issue by cmolendijk** [jeanverster/chakra-ui-steps#36]
When loading on a smaller screen. The initial load is always in horizontal mode. 
![image](https://user-images.githubusercontent.com/2002959/143549883-3b554595-0534-4b88-8657-84798ed69f81.png)

When changing orientation of the device to horizontal and then to vertical again. Then the stepper goes into vertical orientation.
![image](https://user-images.githubusercontent.com/2002959/143550029-fb2dde5a-b8c3-4417-bdd3-f3e64fc0260d.png)

**Expected behaviour:** Directly in vertical orientation when initialised on smaller screens

**Comment by jeanverster** [comment]
Hi @cmolendijk - I can't seem to reproduce the issue? Which device size are you testing on? On the demo site I am getting vertical on first load on most mobile devices in portrait orientation

**Comment by jeanverster** [comment]
Another question, are you using SSR in your app?

**Comment by cmolendijk** [comment]
No we use static site generation. But because we could not fix this we stopped using this stepper and made our own component.
