### ISSUE TITLE
custom icon stroke width?

### ISSUE THREAD

**Issue by samhstein** [jeanverster/chakra-ui-steps#38]
hi,

is there a way to change the strokeWidth via the theme settings? using custom icons and would
like to make it 1px.

thanks, sam

const baseStyleIcon: SystemStyleObject = {
  strokeWidth: '2px',
};

**Comment by jeanverster** [comment]
Hey @samhstein, yes this should be possible by providing custom styles for the `icon` part:

```js
import { StepsStyleConfig } from 'chakra-ui-steps'

const CustomSteps = {
  ...StepsStyleConfig,
  baseStyle: () => {
    return {
      icon: {
        strokeWidth: '1px',
      },
    };
  },
};

const theme = extendTheme({
  components: {
    Steps: CustomSteps,
  },
});
```

Let me know if you're still running into issues 👍🏼

**Comment by samhstein** [comment]
hmm,

that smashes the green circle but doesnt change the strokeWidth of the MdIcon inside the circle...

thanks, sam

**Comment by jeanverster** [comment]
@samhstein which icon lib are you using? I've just tried with `react-icons/fi` and seems to work as expected:
![image](https://user-images.githubusercontent.com/17738943/147729682-0c823031-2077-405b-8e48-12c39e57d6c3.png)

**Comment by samhstein** [comment]
import { MdOutlineShoppingCart, MdOutlineLocalShipping, MdOutlineContentPaste, MdAttachFile } from 'react-icons/md';

<img width="619" alt="Screen Shot 2021-12-30 at 12 15 54 AM" src="https://user-images.githubusercontent.com/4429838/147729871-877c0949-718a-457a-a409-c1dd6a48789a.png">
<img width="617" alt="Screen Shot 2021-12-30 at 12 15 28 AM" src="https://user-images.githubusercontent.com/4429838/147729875-6b326c82-d273-41ac-9740-a732773c61de.png">

**Comment by jeanverster** [comment]
Hi @samhstein - really sorry for the delayed reply, I had been on vacation and only getting back into things now. Could you try something like this:
```js
const CustomSteps = {
  ...StepsStyleConfig,
  baseStyle: props => {
    return {
      ...StepsStyleConfig.baseStyle(props),
      icon: {
        ...StepsStyleConfig.baseStyle(props).icon,
        // your custom styles here
        strokeWidth: '1px',
      },
    };
  },
};

const theme = extendTheme({
  components: {
    Steps: CustomSteps,
  },
});
```
I think the reason some of the styles were getting removed was because we werent spreading the original basestyles

**Comment by jeanverster** [comment]
Closing this for now, happy to re-open if the above doesn't solve your issue
