### ISSUE TITLE
 Cannot read properties of undefined (reading 'width') on Step component typescript

### ISSUE THREAD

**Issue by LitHaxor** [jeanverster/chakra-ui-steps#45]
To reproduce use nextjs 12.^

  <Step label={label} key={label}> // Trowing error 
               {content}
  </Step>

**Comment by jeanverster** [comment]
Hi, could you please provide a codesandbox which shows the relevant issue? I have just tried locally using a fresh install of nextjs 12 and I'm not running into any issues

**Comment by LitHaxor** [comment]
Sorry, I forgot to extend the theme.
