### ISSUE TITLE
Styling active label text

### ISSUE THREAD

**Issue by siminn-asdisj** [jeanverster/chakra-ui-steps#50]
Is it possible to change the color and font weight of the default numerical indicator that is **active**?

I'm trying to go from this:

<img width="587" alt="Screenshot 2022-02-21 at 12 21 30" src="https://user-images.githubusercontent.com/71439441/154954379-a2bcc525-ceac-4476-8781-710ceb8f4f8e.png">

To this:

<img width="593" alt="Screenshot 2022-02-21 at 12 19 15" src="https://user-images.githubusercontent.com/71439441/154954276-ec920acf-f04d-4abf-b1d4-f6f0e9a83d63.png">

I've tried styling it with
```
label: {
  _activeStep: {
    fontWeight: 700,
    color: #000000,
  }
}

```
(and also `_active` instead of `_activeStep`) but that isn't working.

**Comment by jeanverster** [comment]
Hey @siminn-asdisj you should be able to achieve this by styling the `span` element inside `stepIconContainer`:
```js
stepIconContainer: {
  ...YourStyles,
  '& span': {
      fontWeight: '900',
   },
}
```
