### ISSUE TITLE
Can pass styling to step label and step description

### ISSUE THREAD

**Issue by frailbongat** [jeanverster/chakra-ui-steps#52]

**Comment by frailbongat** [comment]
@jeanverster what do you think of this? Would also love to work on it. I'm currently using this component Great job. This integrates well on chakra.

**Comment by jeanverster** [comment]
Hey @frailbongat - this should already be possible, by styling the `label` and `description` parts.. See example:
```js
const CustomSteps = {
  ...StepsStyleConfig,
  baseStyle: props => {
    return {
      ...StepsStyleConfig.baseStyle(props),
      label: {
        ...StepsStyleConfig.baseStyle(props).label,
        // your custom label styles here
      },
      description: {
        ...StepsStyleConfig.baseStyle(props).description,
        // your custom description styles here
      },
    };
  },
};
```

**Comment by frailbongat** [comment]
Nice, haven't seen a documentation for this. Cool if we add one?

**Comment by jeanverster** [comment]
It is in the readme, but feel free to update / add anything if it's not clear :) Happy to accept PRs
