### ISSUE TITLE
Add support for React javascript (right now it is only typescript)

### ISSUE THREAD

**Issue by kkeval** [jeanverster/chakra-ui-steps#6]

**Comment by jeanverster** [comment]
Hey @kkeval could you be more specific? Are you referring to the docs, or the library itself that doesn't work in a javascript project? AFAIK it should work fine in regular javascript projects 🤷🏼‍♂️

**Comment by kkeval** [comment]
Add docs/ guide for JavaScript or React I'm not familiar with typescript and also
There is no code for ```
<StepsButton/> 
``` 
``` 
<ResetButton/>
```

**Comment by jeanverster** [comment]
Yeah I can have a look at implementing this, thanks for the suggestion!

**Comment by kkeval** [comment]
> Yeah I can have a look at implementing this, thanks for the suggestion!

Cool, waiting for it!

**Comment by kkeval** [comment]
closed
