### ISSUE TITLE
React not defined in build while loading component with chakra-ui-steps

### ISSUE THREAD

**Issue by RS2007** [jeanverster/chakra-ui-steps#66]
- In my project, I have a button that opens a modal with chakra-ui steps 
- Image shown below:
![image](https://user-images.githubusercontent.com/83483297/166135827-a407a2e4-ee54-431c-aaa7-8322f49c3ed5.png)
- This is from the development environment(vite)
- After building the app(vite build), when I try to access the modal(by clicking the button), i get this error:
![image](https://user-images.githubusercontent.com/83483297/166135896-0a1ca384-e4ab-412c-b729-35b232d4733e.png)
- I think this is an issue with chakra-ui-steps because all the other packages are being used in other components within the same project and they all seem to work fine in the build

**Comment by jeanverster** [comment]
Hi! Thanks for raising this. Any chance you could send a minimal reproduction that I could have a look at? Otherwise it's quite difficult for me to diagnose what's wrong

**Comment by RS2007** [comment]
- You can clone this repo and try building it, thats where the error was popping up,
[repo](https://github.com/RS2007/SocialMediaApp)

- As for minimal reproduction, I guess try initialising a vite react app and then using chakra ui steps and then preview the build
