### ISSUE TITLE
I can not set .chakra-collapse: overflow hidden to overflow unset.

### ISSUE THREAD

**Issue by MartinGiordano** [jeanverster/chakra-ui-steps#72]
Hey everyone, recently y was implementing this stepper and i came to a wall when y want to display a popover inside a vertical stepper.

There is a div with class of .chakra-collapse, that has a css overflow property set to hidden.

I'd tryed :
- To add custom styling to a Step component.
- Config a global object inside my theme stylesConfigs.
- Wrap the Step component on container with styled div but it broke the ui.

but i can not overide  succesfully that property.

¿have the Step Component a way to make this happen via props or anothersolution?

<img width="536" alt="Captura de Pantalla 2022-06-03 a la(s) 00 33 10" src="https://user-images.githubusercontent.com/46050882/171780995-edda70e5-543f-4020-92af-8e8326244ad0.png">

**Comment by jeanverster** [comment]
Hi @MartinGiordano this seems to be from the default styles applied to the chakra `Collapse` component, which is being used in the vertical stepper. Can you provide a snippet of the code that's causing the issues? I just tried a simple example using a popover in a vertical step and it works as expected.
