### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by marcos-bueno** [jeanverster/chakra-ui-steps#79]
```
"dependencies": {
    "@chakra-ui/icons": "^1.1.7",
    "@chakra-ui/react": "^1.8.8",
    "@emotion/react": "^11.1.5",
    "@emotion/styled": "^11.1.5",
    "chakra-ui-steps": "^1.3.0",
    "framer-motion": "^6.3.11",
    "next": "10.2.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
  }
```
<img src="https://tinypng.com/web/output/090tjx5mjutxut3115kg8n4bfr6w5guj/Captura%20de%20Tela%202022-08-02%20a%CC%80s%2022.48.32.png">
<img src="https://tinypng.com/web/output/b2fd8jqt6m0ub9rt4fmcv1t2k016vwz5/Captura%20de%20Tela%202022-08-02%20a%CC%80s%2023.06.43.png">

**Comment by guanghw** [comment]
I have the same problem, how did you solve it please?
