### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by ablaszkiewicz** [jeanverster/chakra-ui-steps#80]
Hi.

These are my dependencies:
```
"@chakra-ui/icons": "^2.0.6",
"@chakra-ui/react": "^2.2.6",
"@emotion/react": "^11.10.0",
"@emotion/styled": "^11.10.0",
"@types/react": "^18.0.15",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"framer-motion": "^6.0.0",
"chakra-ui-steps": "^1.7.3",
```

I tried copying first code example from docs and it threw this error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'width')
```

So I tried to strip it down to minimal code
```
<Steps activeStep={0}>
  <Step>
    <Text>Hello</Text>
  </Step>
</Steps>
```

And it still throws the same error. Not sure how beneficial this would be but it shows error here

![image](https://user-images.githubusercontent.com/54682207/183065720-f3fa05b0-7208-4ac3-ab5e-907b2463c607.png)

Any clue what is going on and how to fix it?

**Comment by jeanverster** [comment]
Hi! This seems to be quite a common issue, think I will add a section in the readme around this.. But it's likely you forgot the extend the chakra theme with the `Steps` configuration:

```jsx
import { ChakraProvider, extendTheme } from '@chakra-ui/react';
import { StepsStyleConfig as Steps } from 'chakra-ui-steps';

const theme = extendTheme({
  components: {
    Steps,
  },
});

export const App = () => {
  return (
    <ChakraProvider theme={theme}>
      <App />
    </ChakraProvider>
  );
};
```

**Comment by ablaszkiewicz** [comment]
Thank you very much. I was about to change my profession to hair dresser.
