### ISSUE TITLE
Contents is not defined

### ISSUE THREAD

**Issue by tiganabryan** [jeanverster/chakra-ui-steps#84]
# Error: Cannot find name 'Contents'

## Reproduction: https://codesandbox.io/s/still-hooks-vc25zs?file=/src/Horizontal.tsx

<img src="https://i.imgur.com/W9aGmdU.png" alt="screenshot of error">

### Screenshot of interactive demo's code
<img src="https://i.imgur.com/CuHIEjr.png" alt="screenshot of Contents component in interactive demo">

<img src="https://i.imgur.com/KLZGNIn.png" alt="screenshot of first stepper on chakra-ui-steps site">

**Comment by jeanverster** [comment]
Hey @tiganabryan sorry if the examples aren't super clear, but the `<Content />` component is actually just a placeholder for whatever you would want to render inside the steps :) For example you could do something like this:
```jsx
{steps.map(({ label }, index) => (
  <Step label={label} key={label}>
    <div>Step {index + 1}</div>
  </Step>
))}
```
I realise this is maybe a bit confusing so I think I will actually update these examples to be a bit more clear

**Comment by tiganabryan** [comment]
Oh ok thanks for clarifying. The stepper is really smooth and seamless, you did a great job.
