### ISSUE TITLE
Custom error icon

### ISSUE THREAD

**Issue by branislaav** [jeanverster/chakra-ui-steps#90]
I would like to pass a custom error icon to Steps component same way that you can pass a custom check icon through `checkIcon` prop. I can make PR for that if it is okay.

**Comment by moosefaceee** [comment]
Hi @branislaav & @jeanverster 

Implemented the above in the PR mentioned 👆🏼 #hacktoberfest

**Comment by jeanverster** [comment]
Released in v2
