### ISSUE TITLE
Upgrade to react 18 and Charka v2

### ISSUE THREAD

**Issue by tejans24** [jeanverster/chakra-ui-steps#91]
Hi @jeanverster or anyone else, have you tried upgrading React and Charka to newer versions?

**Comment by jeanverster** [comment]
Hi @tejans24 I'm currently working on v2 of this component which will include react 18 & chakra 2 support amongst other things.. I'm almost done, should hopefully have it done this weekend sometime!

**Comment by tejans24** [comment]
> Hi @tejans24 I'm currently working on v2 of this component which will include react 18 & chakra 2 support amongst other things.. I'm almost done, should hopefully have it done this weekend sometime!

Great thanks @jeanverster. Looking forward to seeing that PR soon!

**Comment by LeonAlvarez** [comment]
Any update?

**Comment by WarriorCodeDev** [comment]
Hi @jeanverster any update on this issue?

**Comment by garrylachman** [comment]
have fun :)
https://github.com/jeanverster/chakra-ui-steps/pull/96

**Comment by jeanverster** [comment]
Hey all! This has been released in v2 of `chakra-ui-steps` - let me know if anyone still runs into issues :)
