### ISSUE TITLE
Bug fix reqd: Cannot read properties of undefined (reading 'width') at chakra-ui-steps.es.js:315:25

### ISSUE THREAD

**Issue by balu9230** [jeanverster/chakra-ui-steps#92]
Hi,

I'm sharing a link to a public repo that I created to recreate the issue using the latest version of chakra-ui-steps:
https://github.com/balu9230/issue-chakra-ui-steps
Kindly clone it and read the README file for further details.

Due to this error, the page is, of course, not rendering.

I've used the same example code snippet that you have mentioned on the main repo of chakra-ui-steps inside the file Steps.tsx
This sample project is built using Vite and Typescript. But that's about it.

Happy to help with any further questions that you may have.

**Comment by omoriyasuo** [comment]
Hi, I'm getting this error too.
Is there any solution to this?

environment: 
- `vite: 2.9.15`
- `typescript: 4.6.3`
- `@chakra-ui/react: 11.9.3`

**Comment by omoriyasuo** [comment]
Ah..., I'm guessing it's because we're using `@chakra-ui/react 2.x.x.` 

I tried downgrading @chakra-ui/react: 1.8.8, then it was fine.

**Comment by balu9230** [comment]
Hey @omoriyasuo, no, I tried lowering `@chakra-ui/react` down to 1.8.8 (from 2.3.4), didn't work for me. :(

A few questions for you, if you don't mind:
1. Is 1.8.8 the latest version of `@chakra-ui/react` for which `chakra-ui-steps` would work for you?
2. How would you go about identifying the latest version that you can make do with? Did you try every version number in descending order tediously?
3. Shouldn't these be handled by npm automatically - based on the versions of dependency packages specified by the author?

**Comment by Martinnord** [comment]
Getting this error on,
* `"@chakra-ui/react": "^2.2.4"`
* `"react": "18.2.0"`

**Comment by Martinnord** [comment]
Forgot to post this, but remember adding this to your project,
```tsx
import { ChakraProvider, extendTheme } from '@chakra-ui/react';
import { StepsStyleConfig as Steps } from 'chakra-ui-steps';

const theme = extendTheme({
  components: {
    Steps,
  },
});

export const App = () => {
  return (
    <ChakraProvider theme={theme}>
      <YourApp />
    </ChakraProvider>
  );
};
```
As the documentation says. It will solve this issue.

**Comment by balu9230** [comment]
Hi @Martinnord, yes, thanks. Your comment prompted me to look more closely at this and I realized that the issue was because I had wrapped that theme object with an extra set of curly braces.

This was the faulty code:
`import { ChakraProvider, extendTheme } from "@chakra-ui/react"
import { StepsStyleConfig as Steps } from 'chakra-ui-steps'

const utmfTheme = {
	components: {
		Steps,
	}
}

const theme = extendTheme({ utmfTheme })

export default theme`

and the corrected code:
`import { ChakraProvider, extendTheme } from "@chakra-ui/react"
import { StepsStyleConfig as Steps } from 'chakra-ui-steps'

const utmfTheme = {
	components: {
		Steps,
	}
}

const theme = extendTheme(utmfTheme)

export default theme`

As you can see above, the change is in the line:
`const theme = extendTheme(utmfTheme)`

It renders now and works properly. It was a silly oversight from our end. Apologies.
I will close this issue and hope that it helps posterity.
