### ISSUE TITLE
Getting: ContextError: useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />` 

### ISSUE THREAD

**Issue by devlukedreamstage** [jeanverster/chakra-ui-steps#94]
Hi,

I'm trying to export a component using the stepper using the example and following the instructions, but I'm getting this error. I added steps to the theme as well. The component and my chakraprovider are apart of a monorepo they are being exported from if that could a potential cause.

**Comment by wub** [comment]
Hey @devlukedreamstage I experienced this issue with `@chakra-ui/react` v2.3.6, using v2.3.5 works for me.

**Comment by jeanverster** [comment]
Hi! Closing this issue as I think it has been addressed with a chakra version bump. Please re-open if the issue persists :)
