### ISSUE TITLE
Vertical orientation: if onClickStep is set nextStep and prevStep don't seem to work

### ISSUE THREAD

**Issue by winnekes** [jeanverster/chakra-ui-steps#98]
In vertical orientation _either_ `nextStep/prevStep/setStep` works as intended OR `onClickStep`.
When `onClickStep` is set, I cannot control the wizard's active step via a button click for example.

``` 
<Steps
            activeStep={activeStep}
            onClickStep={(step) => setStep(step)}
            orientation="vertical"
          >
            {steps.map(({ id, label = '', content }, index) => (
              <Step
                key={id}
                textAlign="left"
                label={label}
              >
              {content}

              </Step>
            ))}
          </Steps>
```
         
When I set the orientation to 'horizontal' it works as intended.

**Comment by gyuly89** [comment]
Could you please have a look into this? I am experiencing the same problem and I would like to have both interactions available.

**Comment by JohnnyTheTank** [comment]
I'm using v2.0.4 and experience still the same problem
